[tool.pytest.ini_options]
addopts = "--create-db --migrations"
python_files = "test*.py *tests.py tests*.py *test.py"
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.isort]
known_third_party = ["django", "factory", "pytest", "rest_framework"]
profile = "black"
line_length = 90

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''
